// Strategy League 화면 단위검사에 쓰는 결정적 Registry fixture를 제공한다.
import { initialDashboard } from '../src/demoData'
import type { DashboardData, LeagueAccount, StrategyPerformance, StrategyRow } from '../src/types'

const catalog = [
  ['LSA_REVERSAL_V1', 'LSA 반전', '급락·급등 쓸기 반전'],
  ['CBR_CONTINUATION_V1', 'CBR 돌파', '압축 돌파 재가속'],
  ['VWAP_EXHAUSTION_REVERSION_V1', 'VWAP 소진', 'VWAP 과도이탈 평균복귀'],
  ['OFI_CONTINUATION_PULLBACK_V1', 'OFI 눌림', 'OFI 추세 눌림 지속'],
  ['QUEUE_MICROPRICE_MOMENTUM_V1', '호가 쏠림', '호가 쏠림 순간추세'],
  ['AGGRESSOR_FLOW_CONTINUATION_V1', '체결흐름', '강한 체결 흐름 지속'],
  ['MULTILEVEL_MICROPRICE_MOMENTUM_V1', '다중호가', '다중호가 공정가 추세'],
  ['DEPTH_ADJUSTED_OFI_IMPULSE_V1', '깊이 OFI', '깊이보정 OFI 충격'],
  ['OFI_RETURN_CONFLUENCE_V1', 'OFI·가격동행', 'OFI·단기수익률 동행'],
  ['BOOK_SLOPE_ASYMMETRY_V1', '호가 기울기', '호가 기울기 비대칭'],
  ['HOURLY_MOMENTUM_BREAKOUT_V1', '시간봉 추세', '시간봉 추세 돌파'],
] as const

function performance(strategyId: string, profile: 'BASE' | 'STRESS'): StrategyPerformance {
  return {
    strategy_id: strategyId,
    profile,
    sample_size: 0,
    wins: 0,
    losses: 0,
    breakevens: 0,
    win_rate: null,
    win_rate_ci95: null,
    average_win_usdt: null,
    average_loss_usdt: null,
    payoff_ratio: null,
    expectancy_usdt: null,
    expectancy_r: null,
    expectancy_bps: null,
    profit_factor: null,
    omega_ratio: null,
    sortino_ratio_per_trade: null,
    calmar_ratio_nonannualized: null,
    downside_deviation_usdt: null,
    gross_pnl: '0',
    fees: '0',
    slippage: '0',
    net_pnl: '0',
    cost_burden: null,
    maximum_drawdown: '0',
    turnover_usdt: '0',
    turnover_ratio: '0',
    mae_r_mean: null,
    mfe_r_mean: null,
    median_hold_ms: null,
    p90_hold_ms: null,
    tp1_sample_size: 0,
    tp2_sample_size: 0,
    stop_sample_size: 0,
    median_time_to_tp1_ms: null,
    median_time_to_tp2_ms: null,
    median_time_to_stop_ms: null,
    trail_activation_count: 0,
    trail_activation_rate: null,
    tp1_fill_rate: null,
    runner_count: 0,
    runner_rate: null,
    runner_net_contribution_usdt: '0',
    mfe_capture_ratio_mean: null,
    average_peak_giveback_usdt: '0',
    median_peak_giveback_usdt: '0',
    p90_peak_giveback_usdt: '0',
    trailing_exit_count: 0,
    stop_before_trail_activation_count: 0,
    activation_after_net_negative_exit_count: 0,
    trail_trigger_slippage_usdt: '0',
    regime_contributions: [],
    metric_status: {},
    sample_status: '표본 부족',
    sample_span_days: 0,
    regime_count: 0,
    regimes: [],
    symbols: [],
    sides: { LONG: 0, SHORT: 0 },
    stress_verified: profile === 'STRESS',
    recommendation: '표본 수집',
    recommendation_is_advisory: true,
    analysis_scope: 'CURRENT_STRATEGY_VERSION',
    strategy_version: 'fixture-current',
    excluded_prior_version_samples: 0,
    windows: { recent_50: { sample_size: 0 }, recent_100: { sample_size: 0 }, recent_300: { sample_size: 0 } },
  }
}

export const strategies: StrategyRow[] = catalog.map(([strategyId, shortName, displayName], index) => ({
  strategy_id: strategyId,
  short_name: shortName,
  display_name_ko: displayName,
  summary_ko: '공개시장 구조와 체결 흐름을 PAPER로만 평가합니다.',
  stability: index === 1 ? 'STABLE' : 'EXPERIMENTAL',
  supported_regimes: ['RANGE'],
  exit_style: index === 0 || index === 2 ? 'REVERSION_70_30' : 'TREND_40_60',
  horizon_class: index === 10 ? 'INTRADAY_SWING' : 'MICRO_SCALP',
  expected_holding_seconds: index === 10 ? [3600, 129600] : [10, 180],
  signal_half_life_seconds: index === 10 ? 5 : 30,
  required_timeframes: index === 10 ? ['1h'] : ['250ms', '1s', '3s', '10s', '30s', '120s'],
  exit_model: 'STRUCTURE_TP1_TP2_EDGE_DECAY',
  take_profit_1_r: index === 10 ? '2.2' : '1.5',
  take_profit_2_r: index === 10 ? '4.5' : '3.0',
  entry_rules_ko: index === 10 ? ['완성 1시간봉 200개 이상', 'EMA·모멘텀·돌파·ADX·상대거래량 동시 확인'] : [],
  exit_rules_ko: index === 10 ? ['TP1 2.2R·40%', 'TP2 4.5R·60%'] : [],
  max_hold_seconds: index === 10 ? 129600 : 900,
  cost_model_version: 'TOP_OF_BOOK_BASE13_STRESS25_V1',
  strategy_version: 'V1',
  required_market_data: index === 10
    ? ['완성 공개 1시간봉', 'sequence-valid 공개 bid·ask']
    : ['sequence-valid 공개 top-10 bid·ask', '공개 aggregate trade', '종목별 과거 피처'],
  minimum_warmup_ko: index === 10 ? '완성 1시간봉 200개 이상' : '건전한 종목별 공개시장 10초 이상과 현재 이전 prefix 통계',
  entry_hypothesis_ko: '현재 이전 공개시장 정보가 같은 방향으로 정렬되고 비용 gate를 통과하면 PAPER 후보로 평가합니다.',
  falsification_conditions_ko: ['필수 데이터 또는 방향 정렬 실패', '비용후 순 R:R gate 실패'],
  edge_decay_policy_ko: '진입 후 10초 grace·불리한 근거 2개·3초 지속 뒤 PAPER 관리청산',
  risk_budget_rule_ko: '공동 PAPER 0.10%·독립 PAPER 0.50% 계좌자산 위험예산',
  target_universe_ko: '동적 정밀분석 종목 중 지원 레짐·유동성·비용 gate 통과 종목',
  data_leakage_guards_ko: ['현재 event timestamp 이전의 동일 종목 이력만 사용', '미래 timestamp 입력 fail-closed'],
  research_source_ids: index === 10
    ? ['SRC-CRYPTO-MOMENTUM-2018', 'SRC-BINANCE-KLINE', 'SRC-BINANCE-DEPTH']
    : ['SRC-OFI-2010', 'SRC-BINANCE-DEPTH', 'SRC-BINANCE-AGGTRADE'],
  paper_only: true,
  mode: [0, 3, 4, 7, 10].includes(index) ? 'OFF' : 'SHADOW',
  lifecycle: [0, 3, 4, 7, 10].includes(index) ? 'RETIRED' : 'SHADOW',
  long_enabled: true,
  short_enabled: true,
  settings_revision: 0,
  manual_lock: false,
  changed_by: 'MIGRATION',
  change_reason: 'SAFE_DEFAULT',
  settings_updated_ts_ms: 0,
  policy_reactivation_locked: [0, 3, 4, 7, 10].includes(index),
  evaluated_paths: 0,
  qualified_paths: 0,
  latest_status: 'WAITING_DATA',
  latest_reasons: [],
  governance: {
    strategy_id: strategyId,
    current_lifecycle: [0, 3, 4, 7, 10].includes(index) ? 'RETIRED' : 'SHADOW',
    recommended_lifecycle: [0, 3, 4, 7, 10].includes(index) ? 'RETIRED' : 'SHADOW',
    reason_codes: ['LIVE_PUBLIC_SAMPLE_LT_30'],
    automatic_action_allowed: false,
    transition_required: false,
    champion_id: null,
    last_evaluated_ts_ms: 1_759_888_000_000,
    evaluation_period: 'CURRENT_STRATEGY_VERSION_LIVE_PUBLIC',
    evidence_status: 'NOT_PROVEN',
    remaining_live_samples: 30,
    remaining_days: 7,
    manual_lock: false,
    settings_revision: 0,
    change_history: [],
  },
  performance: {
    BASE: performance(strategyId, 'BASE'),
    STRESS: performance(strategyId, 'STRESS'),
  },
}))

export const leagueAccounts: LeagueAccount[] = strategies.flatMap((strategy, strategyIndex) => (
  (['BASE', 'STRESS'] as const).map((profile) => ({
    account_id: `${strategy.strategy_id}:${profile}`,
    strategy_id: strategy.strategy_id,
    profile,
    starting_equity_usdt: '1000',
    current_equity_usdt: profile === 'BASE' ? String(1000 + strategyIndex) : '1000',
    realized_pnl_usdt: '0',
    unrealized_pnl_usdt: '0',
    fees_usdt: '0',
    slippage_usdt: '0',
    trade_count: 0,
    wins: 0,
    losses: 0,
    win_rate: null,
    open_positions: 0,
    pending_entries: 0,
    gross_notional_usdt: '0',
    effective_leverage: '0',
    maximum_effective_leverage: '5',
    maximum_drawdown_usdt: '0',
    paused: false,
    faulted: false,
  }))
))

export function dashboardFixture(): DashboardData {
  return {
    ...initialDashboard,
    status: { ...initialDashboard.status },
    chart: { ...initialDashboard.chart, points: [], candles: [], lines: { ...initialDashboard.chart.lines } },
    strategies: strategies.map((strategy) => ({ ...strategy })),
    league_accounts: leagueAccounts.map((account) => ({ ...account })),
  }
}
