// 네트워크 응답 전에도 LIVE로 오인되지 않는 최소 fixture 상태를 제공한다.
import type { DashboardData } from './types'

export const initialDashboard: DashboardData = {
  status: {
    mode: 'READY',
    market_data_state: 'DISCONNECTED',
    execution_state: 'PAPER',
    venue: 'NONE',
    run_id: 'ready',
    starting_equity_usdt: 1000,
    current_equity_usdt: 1000,
    realized_pnl_usdt: 0,
    unrealized_pnl_usdt: 0,
    cumulative_fees_usdt: 0,
    cumulative_slippage_usdt: 0,
    trade_count: 0,
    real_orders_enabled: false,
    auth_required: false,
    wide_symbols: 0,
    deep_symbols: 0,
    processing_lag_p95_ms: null,
    health_flags: ['READY_NOT_STARTED'],
  },
  paused: false,
  operation_status: {
    state: 'READY',
    title_ko: '시작 전',
    detail_ko: '자동 관찰 시작을 한 번 누르면 공개시장 연결을 계속 유지합니다.',
    market_observation_active: false,
    paper_entry_active: false,
    automatic_recovery: true,
    recommended_action: 'START',
    lag_p95_ms: null,
  },
  scanner: [],
  chart: {
    symbol: 'BTCUSDT',
    interval: '3m',
    points: [],
    candles: [],
    lines: { entry: null, take_profit: null, stop: null },
    fixture: false,
  },
  position: null,
  logs: [],
  history: [],
  history_scope: {
    analysis_scope: 'CURRENT_STRATEGY_VERSION',
    strategy_version: 'loading',
    excluded_prior_version_samples: 0,
  },
  strategies: [],
  shadow_accounts: [],
  league_accounts: [],
  league_positions: [],
  focus_positions: [],
  control_operation: null,
  performance: {
    sample_size: 0,
    gross_pnl: '0',
    fees: '0',
    slippage: '0',
    net_pnl: '0',
    max_drawdown: '0',
    win_rate: '표본 없음',
    calibration: 'CALIBRATING',
    base_equity: '1000',
    stress_equity: '1000',
  },
  risk: {
    paper_only: true,
    active_locks: ['PAPER_ONLY'],
    immutable_run: true,
    shared_capital: {
      starting_equity_usdt: '1000',
      risk_per_position: '0.10%',
      max_positions: 1,
      daily_loss_limit: '5 USDT',
      weekly_loss_limit: '15 USDT',
      drawdown_lock: '3.00%',
    },
    strategy_league: {
      account_count: 16,
      starting_equity_per_account_usdt: '1000',
      risk_per_position: '0.50%',
      max_positions_per_account: 3,
      maximum_total_open_risk: '1.50%',
      maximum_effective_leverage: '5.00x',
      maximum_depth_fraction: '2.00%',
      daily_loss_limit: '2.00%',
      weekly_loss_limit: '5.00%',
      drawdown_lock: '8.00%',
      base_entry_fee: '6bp',
      base_exit_fee: '6bp',
      stress_entry_fee: '12bp',
      stress_exit_fee: '12bp',
    },
  },
  system: {
    api_host: '127.0.0.1:8765',
    auth_headers: false,
    storage: 'loading',
    app_version: '0.2.0-paper',
  },
}
